services:
  social_media_sensor:
    image: social-media-sensor
    gpus:
      - count: 1
    ports:
      - "8001:8000"
    environment:
        - BLUESKY_HANDLE=${BLUESKY_HANDLE}
        - BLUESKY_PASSWORD=${BLUESKY_PASSWORD}
        - MASTODON_ACCESS_TOKEN=${MASTODON_ACCESS_TOKEN}
        - MASTODON_SERVER=${MASTODON_SERVER}
        - OPENAI_API_KEY=${OPENAI_API_KEY}
        - LLM_ADDRESS=http://vllm:8000/v1
        - MODEL_NAME=Qwen/Qwen2.5-VL-7B-Instruct
    depends_on:
      - vllm
    restart: unless-stopped
  vllm:
    image: "vllm/vllm-openai:latest"
    gpus:
      - count: 1
    runtime: nvidia
    ipc: host
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    command: "--model Qwen/Qwen2.5-VL-7B-Instruct --max_model_len 4028"
    environment:
        - HF_TOKEN=${HF_TOKEN}
    restart: unless-stopped